CREATE TABLE IF NOT EXISTS Product_Category(
id  INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255),
description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Product_Category_Jdbc(
id  INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255),
description VARCHAR(255)
);

CREATE TABLE Supplier(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255)
);

CREATE TABLE Customer(
id   INT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(255),
last_name VARCHAR(255),
user_name VARCHAR(255),
password VARCHAR(255),
email_address VARCHAR(255),
token VARCHAR(255)
);

CREATE TABLE Product(
id   INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255),
description VARCHAR(255),
price DECIMAL,
weight DOUBLE,
category INT NOT NULL REFERENCES Product_Category(id) ON DELETE CASCADE,
supplier INT NOT NULL REFERENCES Supplier(id) ON DELETE CASCADE,
image_url VARCHAR(255)
);

CREATE TABLE Product_Jdbc(
id   INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255),
description VARCHAR(255),
price DECIMAL,
weight DOUBLE,
category INT NOT NULL REFERENCES Product_Category_Jdbc(id) ON DELETE CASCADE,
supplier INT NOT NULL REFERENCES Supplier(id) ON DELETE CASCADE,
image_url VARCHAR(255)
);

CREATE TABLE Address(
id   INT AUTO_INCREMENT PRIMARY KEY,
country VARCHAR(255) NULL,
city VARCHAR(255) NULL,
county VARCHAR(255) NULL,
street_address VARCHAR(255) NULL,
state VARCHAR(255) NULL
);

CREATE TABLE Location (
id   INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255),
address INT NOT NULL REFERENCES Address(id) ON DELETE CASCADE
);

CREATE TABLE Stock(
product INT  NOT NULL REFERENCES Product(id) ON DELETE CASCADE,
location INT NOT NULL REFERENCES Location(id) ON DELETE CASCADE,
quantity INT,
CONSTRAINT pk_product_location PRIMARY KEY (product,location)
);

CREATE TABLE Orders(
id   INT AUTO_INCREMENT PRIMARY KEY,
shipped_from INT NOT NULL REFERENCES Location(id) ON DELETE CASCADE,
customer INT NOT NULL REFERENCES Customer(id) ON DELETE CASCADE,
created_at DATETIME,
address INT NOT NULL REFERENCES Address(id) ON DELETE CASCADE
);

CREATE TABLE Order_Detail(
orders INT NOT NULL REFERENCES Orders(id) ON DELETE CASCADE,
product INT NOT NULL REFERENCES Product(id) ON DELETE CASCADE,
quantity INT,
CONSTRAINT pk_order_product PRIMARY KEY (orders,product)
);

CREATE TABLE Revenue(
id INT  AUTO_INCREMENT PRIMARY KEY,
location INT REFERENCES Location(id) ON DELETE CASCADE,
local_date DATE,
sum DECIMAL
);

CREATE TABLE User_Customer (
username NVARCHAR(64) PRIMARY KEY,
password NVARCHAR(512)NOT NULL,
customer_id INT REFERENCES customer(id) ON DELETE CASCADE
);